# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.

# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: INFO
    io.fouri.wawsup: INFO

spring:
  application:
    name: Wawsup
  profiles:
    # The commented value for `active` can be replaced with valid Spring profiles to load.
    # Otherwise, it will be filled in by maven when building the JAR file
    # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
    active: #spring.profiles.active#
    group:
      dev:
        - dev
        - api-docs
server:
  error:
    include-message: always

springdoc:
  api-docs:
    path: /api-docs

# Used as a basis for in memory tests, use local profile (mvn spring-boot:run -Dspring-boot.run.profiles=local)
# for running against Local Dynamo and dev profile for running against aws hosted DynamoDB
database:
  dao: MemoryDao

amazon:
  access:
    key: bk25d
    secretkey: bkwt8i
  region: localhost
dynamodb:
  endpoint:
    url: http://localhost:8000/
  table-name: wawsup